# Generated by Django 3.2.8 on 2022-06-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_portfolio_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='slug',
            new_name='lug',
        ),
    ]
