# Generated by Django 3.2.8 on 2022-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_slug_portfolio_lug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='lug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
