# Generated by Django 3.2.8 on 2022-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_portfolio_lug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='lug',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
