# Generated by Django 3.2.8 on 2022-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220622_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='title',
        ),
    ]
